services:
  questdb:
    image: questdb/questdb:${QUESTDB_VERSION}
    container_name: ${CONTAINER_NAME}
    env_file:
      - ./.env
    volumes:
      - ./questdb-data:/root/.questdb
    ports:
      - "${QUESTDB_REST_PORT:-9000}:9000"  # REST API
      - "${QUESTDB_INFLUX_PORT:-9009}:9009"  # InfluxDB Line Protocol
      - "${QUESTDB_PG_PORT:-8812}:8812"  # PostgreSQL wire protocol
      - "${QUESTDB_WEB_PORT:-9003}:9003"  # Web Console
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 
      